services:
  accounts:
    image: "swathidoranala/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - testbankntw
  loans:
    image: "swathidoranala/loans:v1"
    container_name: loans-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - testbankntw
  cards:
    image: "swathidoranala/cards:v1"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - testbankntw
networks:
  testbankntw:
    driver: "bridge"